# Generated by Django 6.0.2 on 2026-03-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('1', 'Option 1'), ('2', 'Option 2'), ('3', 'Option 3'), ('4', 'Option 4')], max_length=1, null=True),
        ),
    ]
