# Generated by Django 6.0.2 on 2026-03-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_quizquestion_correct_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='created_at',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='portal.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizoption',
            name='option_text',
            field=models.CharField(max_length=255),
        ),
    ]
