# Generated by Django 6.0.2 on 2026-03-03 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_remove_quizquestion_correct_option_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studymaterial',
            options={},
        ),
        migrations.RemoveField(
            model_name='studymaterial',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='pdf',
            field=models.FileField(default=1, upload_to='materials/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.materialcategory'),
        ),
        migrations.CreateModel(
            name='MaterialDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.studymaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
