# Generated by Django 6.0.2 on 2026-03-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_jobpost_eligibility_jobpost_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='experience',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='skills_required',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
